### ISSUE TITLE
Description 

### ISSUE THREAD

**Issue by tkhaseeb** [jishadp/visionair#2]
php artisan:migrate needs to run first, then php artisan db:seed. (php artisan migrate:seed is not a relevant command)

**Comment by jishadp** [comment]
Please note, its a mistake by typing.
I thought it will be **php artisan migrate --seed**

**Comment by tkhaseeb** [comment]
Yes. this is ok. take care.

**Comment by jishadp** [comment]
Thank You. Can I close the issue ?

**Comment by tkhaseeb** [comment]
Yes, change the description and close issue ;)

**Comment by jishadp** [comment]
Updated Description.
